[package]
name = "tapmove"
version = "1.0.0"
authors = []

[addresses]
tap_market = "0x92c1c3e45c1b40d8902e793b73c8712002200318bd12bb3c289da7345110755c"
pyth      = "0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
wormhole  = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
deployer  = "0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"

[dev-addresses]

[dependencies]
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "main" }

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
