[package]
name = "tapmove"
version = "1.0.0"
authors = []

[addresses]
tap_market = "0xde1f041199f6b745ad17b01bec3e8cd11b6d64a7a034f2baf82b0b478abbaa5d"
pyth      = "0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
wormhole  = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
deployer  = "0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"

[dev-addresses]

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/aptos/contracts"
rev = "main" 

